title: AI哲思录
description: 记录AI相关的思考
theme: minima

markdown: kramdown

# 显示作者（可改为任何你喜欢的名字）
author: ShengdaoJiang
name: ShengdaoJiang
email: jackjiang1989@email.com

# 首页文章列表
paginate: 10

# GitHub Pages 默认插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 网址（自动生成时使用）
url: "https://jackjiang1989.github.io"
